"""Static contract tests for the championship-decider match migration."""

from __future__ import annotations

import re
import unittest
from pathlib import Path


MIGRATIONS_DIR = Path(__file__).resolve().parents[1] / "migrations"
MIGRATION_PATH = MIGRATIONS_DIR / "20260928_add_tournament_decider_matches.sql"
ROLLBACK_PATH = (
    MIGRATIONS_DIR / "20260928_add_tournament_decider_matches_rollback.sql"
)
TABLE = "public.partidos_definicion"
SEQUENCE = "public.partidos_definicion_id_seq"


def sql_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def normalized_sql(path: Path) -> str:
    without_line_comments = re.sub(r"--[^\n]*", "", sql_text(path))
    return re.sub(r"\s+", " ", without_line_comments).strip()


def table_definition() -> str:
    sql = normalized_sql(MIGRATION_PATH)
    match = re.search(
        rf"CREATE TABLE IF NOT EXISTS {re.escape(TABLE)}\s*\((.*?)\)\s*;",
        sql,
        re.IGNORECASE,
    )
    if match is None:
        raise AssertionError(f"Missing CREATE TABLE IF NOT EXISTS {TABLE}")
    return match.group(1)


class DeciderMigrationContractTests(unittest.TestCase):
    def test_migration_is_one_explicit_transaction(self) -> None:
        sql = normalized_sql(MIGRATION_PATH)

        self.assertRegex(sql, re.compile(r"^BEGIN\s*;", re.IGNORECASE))
        self.assertRegex(sql, re.compile(r"COMMIT\s*;$", re.IGNORECASE))
        self.assertEqual(len(re.findall(r"\bBEGIN\s*;", sql, re.IGNORECASE)), 1)
        self.assertEqual(len(re.findall(r"\bCOMMIT\s*;", sql, re.IGNORECASE)), 1)

    def test_table_is_additive_separate_and_rerunnable(self) -> None:
        sql = normalized_sql(MIGRATION_PATH)

        self.assertEqual(
            len(
                re.findall(
                    rf"CREATE TABLE IF NOT EXISTS {re.escape(TABLE)}\s*\(",
                    sql,
                    re.IGNORECASE,
                )
            ),
            1,
        )
        touched_tables = re.findall(
            r"\b(?:CREATE|ALTER|DROP|TRUNCATE)\s+TABLE\s+"
            r"(?:IF\s+(?:NOT\s+)?EXISTS\s+)?([a-z_][a-z0-9_.]*)",
            sql,
            re.IGNORECASE,
        )
        self.assertEqual(set(map(str.lower, touched_tables)), {TABLE})
        self.assertNotRegex(
            sql,
            re.compile(
                r"(?:^|;)\s*(?:INSERT\s+INTO|UPDATE\s+[^;]+\s+SET|DELETE\s+FROM)\b",
                re.IGNORECASE,
            ),
        )

    def test_columns_have_the_required_types_and_nullability(self) -> None:
        definition = table_definition()
        declarations = (
            r"\bid\s+bigint\s+GENERATED BY DEFAULT AS IDENTITY\s+PRIMARY KEY\b",
            r"\bcreated_at\s+timestamptz\s+NOT NULL\s+DEFAULT\s+now\s*\(\s*\)",
            r"\btorneo_id\s+bigint\s+NOT NULL\b",
            r"\bcategoria_id\s+bigint\s+NOT NULL\b",
            r"\blocal_id\s+bigint\s+NOT NULL\b",
            r"\bvisitante_id\s+bigint\s+NOT NULL\b",
            r"\bcampeon_id\s+bigint\s+NOT NULL\b",
            r"\bserie\s+text\s+NOT NULL\b",
            r"\binstancia\s+text\s+NOT NULL\b",
            r"\borden\s+smallint\s+NOT NULL\b",
            r"\bgoles_local\s+smallint\s+NOT NULL\b",
            r"\bgoles_visitante\s+smallint\s+NOT NULL\b",
            r"\bdia\s+date\s+NOT NULL\b",
            r"\bcancha\s+text\s+NOT NULL\b",
            r"\bfuente_url\s+text\s+NOT NULL\b",
        )

        for declaration in declarations:
            with self.subTest(declaration=declaration):
                self.assertRegex(definition, re.compile(declaration, re.IGNORECASE))

    def test_foreign_keys_and_domain_constraints_are_explicit(self) -> None:
        definition = table_definition()
        foreign_keys = {
            "torneo_id": "torneos",
            "categoria_id": "categorias",
            "local_id": "clubes",
            "visitante_id": "clubes",
            "campeon_id": "clubes",
        }

        for column, referenced_table in foreign_keys.items():
            with self.subTest(column=column):
                self.assertRegex(
                    definition,
                    re.compile(
                        rf"FOREIGN KEY\s*\(\s*{column}\s*\)\s*"
                        rf"REFERENCES\s+public\.{referenced_table}\s*\(\s*id\s*\)",
                        re.IGNORECASE,
                    ),
                )

        required_checks = (
            r"CHECK\s*\(\s*local_id\s*<>\s*visitante_id\s*\)",
            r"CHECK\s*\(\s*instancia\s+IN\s*\(\s*'ida'\s*,\s*'vuelta'\s*,\s*'partido_unico'\s*\)\s*\)",
            r"CHECK\s*\(\s*orden\s*>\s*0\s*\)",
            r"CHECK\s*\(\s*goles_local\s*>=\s*0\s*\)",
            r"CHECK\s*\(\s*goles_visitante\s*>=\s*0\s*\)",
            r"UNIQUE\s*\(\s*torneo_id\s*,\s*categoria_id\s*,\s*serie\s*,\s*orden\s*\)",
        )
        for constraint in required_checks:
            with self.subTest(constraint=constraint):
                self.assertRegex(definition, re.compile(constraint, re.IGNORECASE))

    def test_exact_role_privileges_include_service_role_sequence_access(self) -> None:
        sql = normalized_sql(MIGRATION_PATH)
        expected_statements = [
            f"REVOKE ALL PRIVILEGES ON TABLE {TABLE} FROM PUBLIC, anon, authenticated;",
            f"GRANT SELECT ON TABLE {TABLE} TO anon, authenticated;",
            f"GRANT INSERT, UPDATE, DELETE ON TABLE {TABLE} TO authenticated;",
            f"GRANT ALL PRIVILEGES ON TABLE {TABLE} TO service_role;",
            f"REVOKE ALL PRIVILEGES ON SEQUENCE {SEQUENCE} FROM PUBLIC, anon, authenticated;",
            f"GRANT ALL PRIVILEGES ON SEQUENCE {SEQUENCE} TO service_role;",
        ]
        actual_statements = re.findall(
            r"\b(?:REVOKE|GRANT)\s+[^;]+;",
            sql,
            re.IGNORECASE,
        )

        self.assertEqual(
            [statement.upper() for statement in actual_statements],
            [statement.upper() for statement in expected_statements],
        )

    def test_rls_has_exactly_four_rerunnable_policies(self) -> None:
        sql = normalized_sql(MIGRATION_PATH)
        self.assertEqual(
            len(
                re.findall(
                    rf"CREATE POLICY\s+\w+\s+ON\s+{re.escape(TABLE)}\b",
                    sql,
                    re.IGNORECASE,
                )
            ),
            4,
        )
        self.assertRegex(
            sql,
            re.compile(
                rf"ALTER TABLE {re.escape(TABLE)} ENABLE ROW LEVEL SECURITY\s*;",
                re.IGNORECASE,
            ),
        )

        policies = {
            "public_read": r"FOR SELECT TO anon, authenticated USING\s*\(\s*true\s*\)",
            "admin_insert": r"FOR INSERT TO authenticated WITH CHECK\s*\(\s*public\.is_liga_admin\s*\(\s*\)\s*\)",
            "admin_update": r"FOR UPDATE TO authenticated USING\s*\(\s*public\.is_liga_admin\s*\(\s*\)\s*\) WITH CHECK\s*\(\s*public\.is_liga_admin\s*\(\s*\)\s*\)",
            "admin_delete": r"FOR DELETE TO authenticated USING\s*\(\s*public\.is_liga_admin\s*\(\s*\)\s*\)",
        }
        for name, policy_body in policies.items():
            with self.subTest(policy=name):
                drop = re.search(
                    rf"DROP POLICY IF EXISTS {name} ON {re.escape(TABLE)}\s*;",
                    sql,
                    re.IGNORECASE,
                )
                create = re.search(
                    rf"CREATE POLICY {name} ON {re.escape(TABLE)} {policy_body}\s*;",
                    sql,
                    re.IGNORECASE,
                )
                self.assertIsNotNone(drop)
                self.assertIsNotNone(create)
                assert drop is not None and create is not None
                self.assertLess(drop.start(), create.start())


class DeciderRollbackContractTests(unittest.TestCase):
    def test_rollback_is_explicitly_dangerous_and_transactional(self) -> None:
        raw_sql = sql_text(ROLLBACK_PATH)
        sql = normalized_sql(ROLLBACK_PATH)

        self.assertRegex(raw_sql, re.compile(r"--.*\bDANGER\b", re.IGNORECASE))
        self.assertRegex(sql, re.compile(r"^BEGIN\s*;", re.IGNORECASE))
        self.assertRegex(sql, re.compile(r"COMMIT\s*;$", re.IGNORECASE))
        self.assertEqual(len(re.findall(r"\bBEGIN\s*;", sql, re.IGNORECASE)), 1)
        self.assertEqual(len(re.findall(r"\bCOMMIT\s*;", sql, re.IGNORECASE)), 1)

    def test_rollback_drops_only_the_new_table(self) -> None:
        sql = normalized_sql(ROLLBACK_PATH)
        drops = re.findall(
            r"\bDROP\s+(?:TABLE|VIEW|MATERIALIZED\s+VIEW|SEQUENCE|FUNCTION|POLICY)\b[^;]*;",
            sql,
            re.IGNORECASE,
        )

        self.assertEqual(drops, ["DROP TABLE IF EXISTS public.partidos_definicion;"])
        self.assertNotRegex(sql, re.compile(r"\bCASCADE\b", re.IGNORECASE))
        self.assertEqual(
            sql,
            "BEGIN; DROP TABLE IF EXISTS public.partidos_definicion; COMMIT;",
        )


if __name__ == "__main__":
    unittest.main()
