-- Add championship-decider matches without exposing them to regular standings.
BEGIN;

CREATE TABLE IF NOT EXISTS public.partidos_definicion (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    torneo_id bigint NOT NULL,
    categoria_id bigint NOT NULL,
    local_id bigint NOT NULL,
    visitante_id bigint NOT NULL,
    campeon_id bigint NOT NULL,
    serie text NOT NULL,
    instancia text NOT NULL,
    orden smallint NOT NULL,
    goles_local smallint NOT NULL,
    goles_visitante smallint NOT NULL,
    dia date NOT NULL,
    cancha text NOT NULL,
    fuente_url text NOT NULL,
    CONSTRAINT partidos_definicion_torneo_fk
        FOREIGN KEY (torneo_id) REFERENCES public.torneos (id),
    CONSTRAINT partidos_definicion_categoria_fk
        FOREIGN KEY (categoria_id) REFERENCES public.categorias (id),
    CONSTRAINT partidos_definicion_local_fk
        FOREIGN KEY (local_id) REFERENCES public.clubes (id),
    CONSTRAINT partidos_definicion_visitante_fk
        FOREIGN KEY (visitante_id) REFERENCES public.clubes (id),
    CONSTRAINT partidos_definicion_campeon_fk
        FOREIGN KEY (campeon_id) REFERENCES public.clubes (id),
    CONSTRAINT partidos_definicion_distinct_teams
        CHECK (local_id <> visitante_id),
    CONSTRAINT partidos_definicion_instancia_allowed
        CHECK (instancia IN ('ida', 'vuelta', 'partido_unico')),
    CONSTRAINT partidos_definicion_orden_positive
        CHECK (orden > 0),
    CONSTRAINT partidos_definicion_goles_local_non_negative
        CHECK (goles_local >= 0),
    CONSTRAINT partidos_definicion_goles_visitante_non_negative
        CHECK (goles_visitante >= 0),
    CONSTRAINT partidos_definicion_series_order_unique
        UNIQUE (torneo_id, categoria_id, serie, orden)
);

-- Start from no inherited direct access, then grant only the intended role surface.
REVOKE ALL PRIVILEGES ON TABLE public.partidos_definicion FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public.partidos_definicion TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON TABLE public.partidos_definicion TO authenticated;
GRANT ALL PRIVILEGES ON TABLE public.partidos_definicion TO service_role;

-- Identity sequence access is reserved for trusted service-role operations.
REVOKE ALL PRIVILEGES ON SEQUENCE public.partidos_definicion_id_seq FROM PUBLIC, anon, authenticated;
GRANT ALL PRIVILEGES ON SEQUENCE public.partidos_definicion_id_seq TO service_role;

ALTER TABLE public.partidos_definicion ENABLE ROW LEVEL SECURITY;

-- Recreate this table's complete policy set so sequential reruns remain idempotent.
DROP POLICY IF EXISTS public_read ON public.partidos_definicion;
CREATE POLICY public_read ON public.partidos_definicion
    FOR SELECT TO anon, authenticated
    USING (true);

DROP POLICY IF EXISTS admin_insert ON public.partidos_definicion;
CREATE POLICY admin_insert ON public.partidos_definicion
    FOR INSERT TO authenticated
    WITH CHECK (public.is_liga_admin());

DROP POLICY IF EXISTS admin_update ON public.partidos_definicion;
CREATE POLICY admin_update ON public.partidos_definicion
    FOR UPDATE TO authenticated
    USING (public.is_liga_admin())
    WITH CHECK (public.is_liga_admin());

DROP POLICY IF EXISTS admin_delete ON public.partidos_definicion;
CREATE POLICY admin_delete ON public.partidos_definicion
    FOR DELETE TO authenticated
    USING (public.is_liga_admin());

COMMIT;
